server:
  port: 8080
  # allow-cors: false

idrnd:
  voicesdk:
    components:
      antispoof: true
      verify: true
      diarization: true
      aed: true
      media: true
      attributes: true
    verify:
      init-data: "verify/verify_init_data_16k"
      # init-data: "verify/verify_init_data_8k"
      verify-methods: "TI_X_2"
      # verify-method: "TI_X_2, MAP"
      # verify-method: "TI_X"