server:
  port: 8080
  # allow-cors: false

idrnd:
  voicesdk:
    components:
      antispoof: true
      verify: true
      diarization: true
      aed: true
      media: true
      attributes: true
    verify:
      init-data: "verify/TI-mic"
      #init-data: "verify/TI-tel"
      #init-data: "verify/TD-mic"
      #init-data: "verify/TI-universal"
